name: Security Scan (SAST)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bearer:
    name: Bearer
    uses: clicksign/seguranca/.github/workflows/bearersast.yml@main
    with:
      working-directory: "."
      scanner: "sast"
      severity: "critical,high,medium,low"
